### ISSUE TITLE
huawei hilens?

### ISSUE THREAD

**Issue by zxfzqf** [lrjbdss/CenterTrack_2D_train#1]
想问一下，你用在了海思什么型号上的板子？是华为hilens吗？效果怎么样？我想在华为hilens上做个行人跟踪，看论文比较，fairmot 或者 CTracker 会快一些，还没来及验证

**Comment by lrjbdss** [comment]
不是哟，我用的hi3519a

**Comment by lrjbdss** [comment]
> 想问一下，你用在了海思什么型号上的板子？是华为hilens吗？效果怎么样？我想在华为hilens上做个行人跟踪，看论文比较，fairmot 或者 CTracker 会快一些，还没来及验证

不是哟，我用的hi3519a。我现在也在做行人跟踪，重新改进了主干网络。冒昧问下，能分享你的行人数据集么

**Comment by zxfzqf** [comment]
数据集我现阶段都用的开源的，行人数据集crowdhuman, 行人跟踪用的就是MOT Challenge的，公司自有数据量不大且还没标注好，而且由于公司性质原因，公司数据什么都分享不出来
感谢回复
